language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "13"

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules

before_script: lerna bootstrap

script:
  - yarn test
  - lerna run benchmark
